name: socialfeet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.0.6
  geolocator: ^10.1.0
  flutter_spinkit: ^5.0.0

  flutter_dotenv: ^5.1.0 #new
  http: ^1.1.0 #new
  flutter_animate: ^4.2.0  #new
  carousel_slider: ^4.2.1 #new
  riverpod: ^2.3.6 #new
  riverpod_generator: ^2.2.3 #new
  riverpod_annotation: ^2.1.1 #new
  hooks_riverpod: ^2.3.6 #new
  cloud_firestore: ^4.14.0 #juannew
  firebase_storage: ^11.6.0 #juannew
  image_picker: ^1.0.7 #juannew

  cupertino_icons: ^1.0.2 
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_messaging: ^14.7.10
  firebase_database: ^10.4.0
  latlong2: ^0.9.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6


flutter:
  assets:
    - .env
    - ./lib/photos/logo.png
    - ./lib/photos/nophoto.png
  
  uses-material-design: true
