// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO_br8xCbJM4QR154IVPNl8NEycx-YBOY',
    appId: '1:296073509007:web:5183fffb9c1ae32d8b98fa',
    messagingSenderId: '296073509007',
    projectId: 'socialfeet-c8776',
    authDomain: 'socialfeet-c8776.firebaseapp.com',
    storageBucket: 'socialfeet-c8776.appspot.com',
    measurementId: 'G-FF3NVLEQ15',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVArLwO0fheGQmM9xnrvuthynephlWjEE',
    appId: '1:296073509007:android:6c3a6cc4b4282b908b98fa',
    messagingSenderId: '296073509007',
    projectId: 'socialfeet-c8776',
    storageBucket: 'socialfeet-c8776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzdDQNPQsTVZKizVLgJc09L9N2WlEp6-o',
    appId: '1:296073509007:ios:c70082161a41e4a88b98fa',
    messagingSenderId: '296073509007',
    projectId: 'socialfeet-c8776',
    storageBucket: 'socialfeet-c8776.appspot.com',
    iosBundleId: 'com.example.socialfeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzdDQNPQsTVZKizVLgJc09L9N2WlEp6-o',
    appId: '1:296073509007:ios:131d4d58eaab3ff08b98fa',
    messagingSenderId: '296073509007',
    projectId: 'socialfeet-c8776',
    storageBucket: 'socialfeet-c8776.appspot.com',
    iosBundleId: 'com.example.socialfeet.RunnerTests',
  );
}
